services:
  orchestrator:
    build:
      context: ./orchestrator
    container_name: orchestrator_service
    ports:
      - "8000:8000"
    depends_on:
      - data_cleaning
      - sentimental_analysis
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  data_cleaning:
    build:
      context: ./data_cleaning
    container_name: data_cleaning_service
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  sentimental_analysis:
    build:
      context: ./sentimental_analysis
    container_name: sentimental_analysis_service
    ports:
      - "8002:8002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  ui:
    build:
      context: ./ui
    container_name: ui_service
    ports:
      - "8501:8501"
    depends_on:
      - orchestrator
